// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: measurement.proto

package protobuf;

public final class MeasurementProtos {
  private MeasurementProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MeasurementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Measurement)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string device_id = 1;</code>
     * @return The deviceId.
     */
    java.lang.String getDeviceId();
    /**
     * <code>string device_id = 1;</code>
     * @return The bytes for deviceId.
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>float temperature = 3;</code>
     * @return The temperature.
     */
    float getTemperature();

    /**
     * <code>float pressure = 4;</code>
     * @return The pressure.
     */
    float getPressure();

    /**
     * <code>float light_level = 5;</code>
     * @return The lightLevel.
     */
    float getLightLevel();

    /**
     * <code>float humidity = 6;</code>
     * @return The humidity.
     */
    float getHumidity();
  }
  /**
   * Protobuf type {@code tutorial.Measurement}
   */
  public  static final class Measurement extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Measurement)
      MeasurementOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Measurement.newBuilder() to construct.
    private Measurement(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Measurement() {
      deviceId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Measurement();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Measurement(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 16: {

              timestamp_ = input.readInt64();
              break;
            }
            case 29: {

              temperature_ = input.readFloat();
              break;
            }
            case 37: {

              pressure_ = input.readFloat();
              break;
            }
            case 45: {

              lightLevel_ = input.readFloat();
              break;
            }
            case 53: {

              humidity_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.MeasurementProtos.internal_static_tutorial_Measurement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.MeasurementProtos.internal_static_tutorial_Measurement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.MeasurementProtos.Measurement.class, protobuf.MeasurementProtos.Measurement.Builder.class);
    }

    public static final int DEVICE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object deviceId_;
    /**
     * <code>string device_id = 1;</code>
     * @return The deviceId.
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <code>string device_id = 1;</code>
     * @return The bytes for deviceId.
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int TEMPERATURE_FIELD_NUMBER = 3;
    private float temperature_;
    /**
     * <code>float temperature = 3;</code>
     * @return The temperature.
     */
    public float getTemperature() {
      return temperature_;
    }

    public static final int PRESSURE_FIELD_NUMBER = 4;
    private float pressure_;
    /**
     * <code>float pressure = 4;</code>
     * @return The pressure.
     */
    public float getPressure() {
      return pressure_;
    }

    public static final int LIGHT_LEVEL_FIELD_NUMBER = 5;
    private float lightLevel_;
    /**
     * <code>float light_level = 5;</code>
     * @return The lightLevel.
     */
    public float getLightLevel() {
      return lightLevel_;
    }

    public static final int HUMIDITY_FIELD_NUMBER = 6;
    private float humidity_;
    /**
     * <code>float humidity = 6;</code>
     * @return The humidity.
     */
    public float getHumidity() {
      return humidity_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceId_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(2, timestamp_);
      }
      if (temperature_ != 0F) {
        output.writeFloat(3, temperature_);
      }
      if (pressure_ != 0F) {
        output.writeFloat(4, pressure_);
      }
      if (lightLevel_ != 0F) {
        output.writeFloat(5, lightLevel_);
      }
      if (humidity_ != 0F) {
        output.writeFloat(6, humidity_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceId_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (temperature_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, temperature_);
      }
      if (pressure_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, pressure_);
      }
      if (lightLevel_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, lightLevel_);
      }
      if (humidity_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, humidity_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.MeasurementProtos.Measurement)) {
        return super.equals(obj);
      }
      protobuf.MeasurementProtos.Measurement other = (protobuf.MeasurementProtos.Measurement) obj;

      if (!getDeviceId()
          .equals(other.getDeviceId())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (java.lang.Float.floatToIntBits(getTemperature())
          != java.lang.Float.floatToIntBits(
              other.getTemperature())) return false;
      if (java.lang.Float.floatToIntBits(getPressure())
          != java.lang.Float.floatToIntBits(
              other.getPressure())) return false;
      if (java.lang.Float.floatToIntBits(getLightLevel())
          != java.lang.Float.floatToIntBits(
              other.getLightLevel())) return false;
      if (java.lang.Float.floatToIntBits(getHumidity())
          != java.lang.Float.floatToIntBits(
              other.getHumidity())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTemperature());
      hash = (37 * hash) + PRESSURE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPressure());
      hash = (37 * hash) + LIGHT_LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLightLevel());
      hash = (37 * hash) + HUMIDITY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHumidity());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.MeasurementProtos.Measurement parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.MeasurementProtos.Measurement parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.MeasurementProtos.Measurement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.MeasurementProtos.Measurement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.MeasurementProtos.Measurement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.MeasurementProtos.Measurement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.MeasurementProtos.Measurement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.MeasurementProtos.Measurement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.MeasurementProtos.Measurement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.MeasurementProtos.Measurement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.MeasurementProtos.Measurement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.MeasurementProtos.Measurement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.MeasurementProtos.Measurement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Measurement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Measurement)
        protobuf.MeasurementProtos.MeasurementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.MeasurementProtos.internal_static_tutorial_Measurement_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.MeasurementProtos.internal_static_tutorial_Measurement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.MeasurementProtos.Measurement.class, protobuf.MeasurementProtos.Measurement.Builder.class);
      }

      // Construct using protobuf.MeasurementProtos.Measurement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        deviceId_ = "";

        timestamp_ = 0L;

        temperature_ = 0F;

        pressure_ = 0F;

        lightLevel_ = 0F;

        humidity_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.MeasurementProtos.internal_static_tutorial_Measurement_descriptor;
      }

      @java.lang.Override
      public protobuf.MeasurementProtos.Measurement getDefaultInstanceForType() {
        return protobuf.MeasurementProtos.Measurement.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.MeasurementProtos.Measurement build() {
        protobuf.MeasurementProtos.Measurement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.MeasurementProtos.Measurement buildPartial() {
        protobuf.MeasurementProtos.Measurement result = new protobuf.MeasurementProtos.Measurement(this);
        result.deviceId_ = deviceId_;
        result.timestamp_ = timestamp_;
        result.temperature_ = temperature_;
        result.pressure_ = pressure_;
        result.lightLevel_ = lightLevel_;
        result.humidity_ = humidity_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.MeasurementProtos.Measurement) {
          return mergeFrom((protobuf.MeasurementProtos.Measurement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.MeasurementProtos.Measurement other) {
        if (other == protobuf.MeasurementProtos.Measurement.getDefaultInstance()) return this;
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getTemperature() != 0F) {
          setTemperature(other.getTemperature());
        }
        if (other.getPressure() != 0F) {
          setPressure(other.getPressure());
        }
        if (other.getLightLevel() != 0F) {
          setLightLevel(other.getLightLevel());
        }
        if (other.getHumidity() != 0F) {
          setHumidity(other.getHumidity());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.MeasurementProtos.Measurement parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.MeasurementProtos.Measurement) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object deviceId_ = "";
      /**
       * <code>string device_id = 1;</code>
       * @return The deviceId.
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string device_id = 1;</code>
       * @return The bytes for deviceId.
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string device_id = 1;</code>
       * @param value The deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string device_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>string device_id = 1;</code>
       * @param value The bytes for deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 2;</code>
       * @return The timestamp.
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 2;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private float temperature_ ;
      /**
       * <code>float temperature = 3;</code>
       * @return The temperature.
       */
      public float getTemperature() {
        return temperature_;
      }
      /**
       * <code>float temperature = 3;</code>
       * @param value The temperature to set.
       * @return This builder for chaining.
       */
      public Builder setTemperature(float value) {
        
        temperature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float temperature = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTemperature() {
        
        temperature_ = 0F;
        onChanged();
        return this;
      }

      private float pressure_ ;
      /**
       * <code>float pressure = 4;</code>
       * @return The pressure.
       */
      public float getPressure() {
        return pressure_;
      }
      /**
       * <code>float pressure = 4;</code>
       * @param value The pressure to set.
       * @return This builder for chaining.
       */
      public Builder setPressure(float value) {
        
        pressure_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float pressure = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPressure() {
        
        pressure_ = 0F;
        onChanged();
        return this;
      }

      private float lightLevel_ ;
      /**
       * <code>float light_level = 5;</code>
       * @return The lightLevel.
       */
      public float getLightLevel() {
        return lightLevel_;
      }
      /**
       * <code>float light_level = 5;</code>
       * @param value The lightLevel to set.
       * @return This builder for chaining.
       */
      public Builder setLightLevel(float value) {
        
        lightLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float light_level = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLightLevel() {
        
        lightLevel_ = 0F;
        onChanged();
        return this;
      }

      private float humidity_ ;
      /**
       * <code>float humidity = 6;</code>
       * @return The humidity.
       */
      public float getHumidity() {
        return humidity_;
      }
      /**
       * <code>float humidity = 6;</code>
       * @param value The humidity to set.
       * @return This builder for chaining.
       */
      public Builder setHumidity(float value) {
        
        humidity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float humidity = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearHumidity() {
        
        humidity_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Measurement)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Measurement)
    private static final protobuf.MeasurementProtos.Measurement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.MeasurementProtos.Measurement();
    }

    public static protobuf.MeasurementProtos.Measurement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Measurement>
        PARSER = new com.google.protobuf.AbstractParser<Measurement>() {
      @java.lang.Override
      public Measurement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Measurement(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Measurement> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Measurement> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.MeasurementProtos.Measurement getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Measurement_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Measurement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021measurement.proto\022\010tutorial\"\201\001\n\013Measur" +
      "ement\022\021\n\tdevice_id\030\001 \001(\t\022\021\n\ttimestamp\030\002 " +
      "\001(\003\022\023\n\013temperature\030\003 \001(\002\022\020\n\010pressure\030\004 \001" +
      "(\002\022\023\n\013light_level\030\005 \001(\002\022\020\n\010humidity\030\006 \001(" +
      "\002B)\n\024protobufB\021MeasurementPr" +
      "otosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_Measurement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Measurement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Measurement_descriptor,
        new java.lang.String[] { "DeviceId", "Timestamp", "Temperature", "Pressure", "LightLevel", "Humidity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
